export const environment = {
  production: true, twitter_image: '../../../assets/Logo+144-144.jpg', share_image: '../../../assets/Logo+540-282.jpg',
  api_url: 'https://api.influxhostserver.com/',
  download_url: 'https://api.influxhostserver.com/download',
  download_url_old: 'https://api.influxhostserver.com/',
  // downloadurl_2:'https://cmte4jq8y5.execute-api.us-east-1.amazonaws.com/production/api/download',
  serverfileurl: 'https://www.betoparedes.com/betoparedesbackend/uploads/',
  // productid: '5d45a11d0d3c2806e4528ffd',
  productid: '5d7f16463bd1bb6d1d19359b',
  awstrainingid: '5d7f23843bd1bb6d1d19359f',
  mdstocktrainingid: '5dbc2f4e22d98f6286d2b00a',
  mdstockServerUrl: 'https://i1kzfac3pe.execute-api.us-east-1.amazonaws.com/dev/api/',
  landing_api_url: 'https://z2oo2a8oq9.execute-api.us-east-1.amazonaws.com/dev/',
  api_calender_url: 'https://m9mkuic6o9.execute-api.us-east-1.amazonaws.com/dev/beto-paredes-api/',
};
